# -*- coding: utf-8 -*-

URL_API_REST_SANDBOX = ''
URL_API_BANK_SANDBOX = ''
URL_API_OAUTH_SANDBOX = ''
URL_APPLI_SANDBOX = ''
URL_STATIC_SANDBOX = ''
URL_CACHE_SANDBOX = ''

URL_API_REST_RELEASE = ''
URL_API_BANK_RELEASE = ''
URL_API_OAUTH_RELEASE = ''
URL_APPLI_RELEASE = ''
URL_STATIC_RELEASE = ''
URL_CACHE_RELEASE = ''
